# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e956c1f9d0a59a905c8a07cb4ac16ce20c5ccb559ef988a05811b8de36efcddf916c81e077e1b9d91ab652acef48994ce5433e75e814b77fe4352d69203d817

test:
  secret_key_base: 4931090a8ff4e93c1ef9ea847e955303a897ae1d93d5bf5c959fb50f321f11935a3aab2a7933e014c756517a6de47b37b6098882564fdd07e76abfff3aa02bc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
